import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  centerContainer: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: '#f5f5f5' },
  header: { backgroundColor: '#007bff', padding: 15, paddingTop: 40, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: 'white' },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  logoutBtn: { backgroundColor: '#dc3545', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 5 },
  logoutText: { color: 'white', fontWeight: '600' },
  loginBtn: { backgroundColor: '#28a745', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 5, marginRight: 10 },
  loginText: { color: 'white', fontWeight: '600', fontSize: 14 },
  title: { fontSize: 28, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  section: { padding: 15, backgroundColor: 'white', marginBottom: 10 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 10 },
  card: { padding: 15, backgroundColor: 'white', borderRadius: 10, marginBottom: 10, marginHorizontal: 15, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  cardTitle: { fontSize: 18, fontWeight: '600', marginBottom: 4 },
  cardSubtitle: { fontSize: 14, color: '#666' },
  label: { fontSize: 16, marginBottom: 5, fontWeight: '600' },
  value: { fontWeight: 'normal', color: '#444' },
  input: { borderWidth: 1, borderColor: '#ddd', padding: 12, borderRadius: 8, marginBottom: 15, backgroundColor: 'white' },
  btn: { backgroundColor: '#007bff', padding: 15, borderRadius: 10, alignItems: 'center', marginBottom: 10, marginHorizontal: 15 },
  btnText: { color: 'white', fontSize: 16, fontWeight: '600' },
  addBtn: { backgroundColor: '#28a745', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 5 },
  addBtnText: { color: 'white', fontWeight: '600', fontSize: 14 },
  productRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  productActions: { flexDirection: 'row', gap: 8 },
  flex1: { flex: 1 },
  editBtn: { backgroundColor: '#ffc107', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 5 },
  editBtnText: { color: '#000', fontWeight: '600', fontSize: 12 },
  deleteBtn: { backgroundColor: '#dc3545', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 5 },
  deleteBtnText: { color: 'white', fontWeight: '600', fontSize: 12 },
});
